version: '3.2'

services:
  agent:
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
        #resources:
        #  limits:
        #    cpus: '1.0'
        #    memory: '40M'
        #  reservations:
        #    cpus: '0.75'
        #    memory: '25M'
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:2.17.1-alpine
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
        #resources:
        #  limits:
        #    cpus: '1.0'
        #    memory: '75M'
        #  reservations:
        #    cpus: '0.5'
        #    memory: '50M'
      replicas: 1
      placement:
        constraints: [node.role == manager]

volumes:
  portainer_data:

networks:
  agent_network:
    driver: overlay
    attachable: true
